### ISSUE TITLE
Dependency to outdated Google API client library

### ISSUE THREAD

**Issue by Kryniol** [xsolve-pl/xsolve-google-auth-bundle#9]
Currently the bundle is dependent on 0.6 version of the client library, this should be migrated to 1.0.0 following the [documentation](https://developers.google.com/api-client-library/php/guide/migration).

**Comment by alanbem** [comment]
Shouldn't be this bundle dropped in favour of https://github.com/hwi/HWIOAuthBundle ?

**Comment by Kryniol** [comment]
Unfortunately, we do still use it in some projects and switching to HWIOAuthBundle would require almost complete rewrite. For me easier will be to maintain it yet for a while :)
And IMHO there are valid cases when using HWIOAuth is an overkill, this bundle is really huge and if you'd like to simply allow logging in using Google oAuth, you don't need all the other providers. And finally, have you ever tried using it along with FOSUserBundle? Still waiting for docs :)

**Comment by alanbem** [comment]
Indeed HWIOAuth doesn't provide enough extension points to work with easily.

**Comment by alanbem** [comment]
I deleted my previous question because I've noticed that this bundle have some additional features over the HWIOAuthBundle
